name: testCupertino
description: Testing Cupertino Layout

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^2.4.0
  flutter: ^1.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: 0.7.2
  # pedantic: ^1.9.2
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  provider: ^4.1.1
  dynamic_theme: ^1.0.1
  flutter_colorpicker: ^0.3.4
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  url_launcher: ^5.5.0
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1

dev_dependencies:
  pedantic: ^1.9.0
  hive_generator: ^0.7.1
  flutter_test:
      sdk: flutter
  # build_runner: ^1.10.2

flutter_icons:
    android: false
    ios: true
    image_path: "assets/icon.png"

flutter_launcher_name:
    name: "LED Controller"

flutter:
  uses-material-design: true
